### ISSUE TITLE
no error

### ISSUE THREAD

**Issue by antwanchild** [traefik/whoami#145]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/whoami/issues) and didn't find any.

### What did you do?

i spin up the container in docker and whoami.mydomain.com works.  But then when i try whoami.mydomain.com/thispagedoesntexist i still get the same whoami.mydomain.com page

### What were you expecting?

i was expecting to get a 404 error

### What version are you using?

v1.11

### What is your environment & configuration?

```yaml
services:
  whoami:
    container_name: "${WHOAMI_NAME:-whoami}"
    image: "${WHOAMI_REGISTRY:-docker.io}/${WHOAMI_IMAGE:-traefik/whoami}${WHOAMI_TAG:-:latest}"
    restart: 'unless-stopped'
    environment:
      TZ: "${TZ:-America/Boise}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${WHOAMI_NAME:-whoami}.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.${WHOAMI_NAME:-whoami}.entryPoints=websecure"
      - "traefik.http.routers.${WHOAMI_NAME:-whoami}.tls=true"
      - "traefik.http.routers.${WHOAMI_NAME:-whoami}.tls.certResolver=${ACME_RESOLVER_NAME:-default}"
```

Add more configuration information here.
