### ISSUE TITLE
whoami pods unable to start

### ISSUE THREAD

**Issue by bgounon** [traefik/whoami#47]
Hello,
We're running whoami for testing purposes on our K8S Cluster, using latest DockerHub image.
We're seeing a new issue today that we didn't have before.
Pods fail to start with the following logs:
```
Starting up on port tcp://10.100.7.29:80
2021/12/03 16:44:43 listen tcp: address :tcp://10.100.7.29:80: too many colons in address
```

I see there has been a new release today, is it related ?
I can reproduce at will by simply pushing the following configuration to a K8S cluster:
```yml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: whoami
  labels:
    app: traefiklabs
    name: whoami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: traefiklabs
      task: whoami
  template:
    metadata:
      labels:
        app: traefiklabs
        task: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
  annotations:
    traefik.ingress.kubernetes.io/service.sticky: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "StickyCookie"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "false"
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: traefiklabs
    task: whoami

---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: whoami
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: whoami
              servicePort: 80
```

Edit: using image traefik/whoami:v1.6.1 fixes the issue

**Comment by bgounon** [comment]
using image traefik/whoami:v1.6.1 fixes the issue

**Comment by ldez** [comment]
Hello,

It doesn't seem related to the new version, the problem is related to the fact the `port` flag is filled by an address instead of a port.
```
# version v1.5.0
whoami -port tcp://10.100.7.29:80
Starting up on port tcp://10.100.7.29:80
2021/12/03 18:32:25 listen tcp: address :tcp://10.100.7.29:80: too many colons in address
exit status 1

# version v1.6.0
whoami -port tcp://10.100.7.29:80
Starting up on port tcp://10.100.7.29:80
2021/12/03 18:31:42 listen tcp: address :tcp://10.100.7.29:80: too many colons in address
exit status 1

# version v1.7.0
whoami -port tcp://10.100.7.29:80
Starting up on port tcp://10.100.7.29:80
2021/12/03 18:34:04 listen tcp: address :tcp://10.100.7.29:80: too many colons in address
exit status 1
```

Maybe you have an env var called `WHOAMI_PORT` with the value `tcp://10.100.7.29:80`

**Comment by ldez** [comment]
It seems related to a k8s behavior.

**Comment by ldez** [comment]
fixed by a067f0ee4c524f380f65ff4b5cb04aff9298d6dd

I will created a bug-fix release.

**Comment by tingwei628** [comment]
After Idez fixed the bug, it worked !!
I added `WHOAMI_PORT_NUMBER` = 8001

```yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
  labels:
    app: whoami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      containers:
        - name: whoami
          image: traefik/whoami
          env:
            - name: WHOAMI_PORT_NUMBER
              value: "8001"
```
